plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
baseurl: /gemini

title: Thingking Machine
description: This is a machine that thingks.
